# Generated by Django 3.1.4 on 2020-12-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0004_car_model_comp_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='login_id',
        ),
        migrations.DeleteModel(
            name='info',
        ),
    ]
