# Generated by Django 3.1.4 on 2020-12-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0005_auto_20201211_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comp_branch',
            new_name='company_branch',
        ),
    ]
