# Generated by Django 3.1.4 on 2020-12-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0006_auto_20201223_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
    ]
